### ISSUE TITLE
Hardcoded `user` model?

### ISSUE THREAD

**Issue by dguettler** [EmberMap/ember-data-storefront#1]
Should this be a dynamic value here?

https://github.com/EmberMap/ember-data-storefront/blob/fd8d7fe42850d65a79d0478553d9fc5c36390b58/addon/mixins/loadable.js#L17

**Comment by ryanto** [comment]
Yikes! Yes... I'll get this fixed right away.

**Comment by ryanto** [comment]
All set: https://github.com/EmberMap/ember-data-storefront/pull/3

**Comment by ryanto** [comment]
Published as version 0.11.0
