### ISSUE TITLE
Cut a new version

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-data-storefront#11]
- [x] Ast rewrite/Linter option for https://github.com/embermap/ember-data-storefront/issues/4
- [x] Move rest of docs from README to site
- [x] Update EmberMap to use latest
- [x] Hide snapshot for now
- [x] use mixin for store.loadAll/store.loadRecord

**Comment by john-griffin** [comment]
So did you settle on store.loadAll/store.loadRecord? That seemed to be what you were showing at Ember NYC but in the code it's saying storefront.findAll/storefront.findRecord https://github.com/embermap/ember-data-storefront/blob/619ce233a43ccc4d282db564a694cc344039278f/addon/services/storefront.js#L134.

**Comment by samselikoff** [comment]
@john-griffin I do think we've settled, we want to use the Mixin approach, which we need to add (today).

Since there's been a lot of churn between `store.loadAll`, `storefront.loadAll` and `storefront.findAll`, we'll support all other with proper deprecation messages until we bump versions.

**Comment by john-griffin** [comment]
Great, thanks for clarifying.

**Comment by samselikoff** [comment]
@john-griffin https://github.com/embermap/ember-data-storefront/pull/15 updates the project with the new `LoadableStore` (and `LoadableModel`) mixins, and you should get deprecation warnings anywhere you're using the old APIs.

Here's the API docs on LoadableStore: https://embermap.github.io/ember-data-storefront/docs/api/LoadableStore-0.11.1+40effca7

Let us know if you have any feedback!

**Comment by john-griffin** [comment]
Thanks! Will check it out.

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-data-storefront/releases/tag/v0.12.0 released.
