### ISSUE TITLE
App does not load with vanilla `ember install ember-data-storefront`

### ISSUE THREAD

**Issue by john-griffin** [embermap/ember-data-storefront#16]
Adding into an app for the first time with `ember install ember-data-storefront` throws an error during load on the following line:

https://github.com/embermap/ember-data-storefront/blob/0f213811c47c2647e826c68c1b7d934b55fd816e/addon/services/storefront.js#L73

This is fixed by adding the store service and mixin as described [here](https://embermap.github.io/ember-data-storefront/docs/api/LoadableStore-0.12.0+7c542282). I guess this either needs to be a mandatory installation step or fixed to be made optional.

**Comment by samselikoff** [comment]
🤦‍♂️  this is my fault

**Comment by samselikoff** [comment]
I think we should just ‘throw’ in the services init function with a message to use the mixin for anyone still relying on the service. Easier than trying to make it work with depredations I think? @ryanto thoughts?

**Comment by ryanto** [comment]
Yup, totally fine.

**Comment by ryanto** [comment]
On second thought, I think the store should automatically be setup with storefront when you install this addon. I can't see anyone wanting to use storefront without the store mixin.

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-data-storefront/releases/tag/v0.12.1 fixes

**Comment by john-griffin** [comment]
Thanks, store now works without configuration in `0.12.1`.
