### ISSUE TITLE
Load relationships without going through includes

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-data-storefront#33]
https://twitter.com/mwpastore/status/969315305863417856

when I do foo.load('bar'), why does it hit `/api/foo/1?include=bar` instead of `/api/foo/1/relationships/bar`? The latter would allow me to e.g. filter foo's bar collection. Maybe storefront needs an additional interface?

**Comment by mwpastore** [comment]
Prior to introducing ember-data-storefront into my app, I would use mdehoog/ember-data-has-many-query to address this need. Maybe we could adapt that functionality into LoadableModel?

**Comment by ryanto** [comment]
Awesome and thanks for reporting this. Sam and I have had a few convos about how to deal with relationship loading.

I took a look at https://github.com/mdehoog/ember-data-has-many-query tonight and think I understand it better. Two quick questions...

1. Is your ideal API to load a relationship with query params from the client? Something like `post.load('comments', { page: 1, filter: { popular: true } });`? Wondering if you have any other use cases or code samples you want to support.
2. Does ember-data-has-many-query also work with storefront. Any code in storefront that's causing trouble for has-many-query or vice-versa?

**Comment by mwpastore** [comment]
> 1. Is your ideal API to load a relationship with query params from the client? 

That's it! 

> 2. Does ember-data-has-many-query also work with storefront. Any code in storefront that's causing trouble for has-many-query or vice-versa?

The problem is that it expects the relationship to be async, so you hit errors like "Uncaught TypeError: reference.load(...).catch is not a function".

**Comment by samselikoff** [comment]
Hey @mwpastore!

Looks like `ember-data-has-many-query` is designed for async relationships – I saw that bug with async: false even without Storefront installed.

You don't have to use async relationships to use other Storefront features, but I know all-sync is one of Storefront's recommendations.

I'm not sure about `has-many-query`'s implementation, but if I wanted to query this collection while still keeping the relationship sync, I think I'd do something like

```
store.query('comments', {
  filter: {
    popular: true,
    postId: post.get('id')
  }
})
```

You don't get to use the relationship `links` in this case but this is how we've done this in the past.

**Comment by mwpastore** [comment]
Hi @samselikoff! Yeah, that's what I'm doing now, but it's not the "natural" {json:api} way to query the relationship, and that's irksome. I know storefront is already working around a bunch of ED hangups so it's understandable if it can't support this use-case. If ED is ever modified to make it possible to load a sync relationship asynchronously on-demand, that would be a good starting point to address this.

**Comment by erichonkanen** [comment]
hey guys, just tried this lib out and ran into this right away where it's making a json-api conventional call to /foo?include=bar which bypasses my related model adapter/buildURL... do I need to change my api?

**Comment by ryanto** [comment]
Thanks @erichonkanen

Right now we are only supporting json:api backends and skipping custom adapters or links payloads. We may change this in the future, but based on how your API is structured I would recommend avoiding using storefront's `load()` method.

**Comment by ryanto** [comment]
I've had a few conversations with folks and I think I have some API changes that will solve a number of these cases.

### Goal

To provide an API for explicitly loading relationship data. This allows for code that is easier to reason about. Calls to `model.get('relationship')` will return whatever data is in the store, while calls to `model.load('relationship')` will fetch data from the backend.

### Current problem

`load('relationship')` uses a JSON:API include query to sideload a models relationship. While this works for standard JSON:API backends, it does not work if the API layer wants the client to use `relationship.links` to load data. 

### Proposed solution

Add `model.sideload('relationship')`. This will work exactly how load works today, it will fetch the model and slideload it's relationship. It will return a cached result if the relationship has already been loaded. Since it is using JSON:API's include parameter to fetch data it has the added benefit of fetching multiple relationships in one go (example: `post.sideload('comments.author,favorites')`).

Change `model.load('relationship')` to use relationship.links. This will allow the client to fetch data from URLs provided by the backend without using the include pattern.

These new APIs will be backwards compatible, if you are using `load()` today it will continue to work.

### Other details

Each of these methods will take an options has as it's last parameter. This will allow for force reloading the relationships data.

```js
model.sideload('relationship', { reload: true });
model.load('relationship', { reload: true });
```

It will also allow developers to implement their own query param logic by overloading the `load` method on a model-by-model basis. Since sending query param data while loading relationships is not supported by ember-data the user will have to write this logic themselves.

**Comment by erichonkanen** [comment]
@ryanto I like it... sounds real good.

**Comment by frank06** [comment]
@ryanto Will the propsed solution honor the overridden methods in the models' adapters? We had issues related to this when we introduced Storefront (i think it was with `loadAll` which ignored our `findAll` adapter customization)

**Comment by frank06** [comment]
Another issue related to `load` which should be fixed by what you suggest, is that `post.load('comments')` would NOT return the actual relationship promise which is important when using this API in a `model` hook for example. I ended up doing this:

```js
    load(rel) {
      return this._super(...arguments).then((model) => {
        return model.get(rel);
      })
    },
```

**Comment by ryanto** [comment]
Thanks for commenting!

1. We think findAll's default behavior can produce unexpected results, so `loadAll` avoids it and its adapter overrides. There's probably a future where we can change this, but we don't do a lot of adapter overriding, so I'd want to see adapter code where storefront causes issues. Also, sorry about that, we should do a better job documenting `loadAll`

To answer your question, the new load that's proposed in this issue should honor adapter code. It will delegate to the references api to load the relationship.

2. Yup great point, new load proposed here will correct this.

**Comment by ryanto** [comment]
I started the PR here https://github.com/embermap/ember-data-storefront/pull/47

**Comment by ryanto** [comment]
Ok, this feature has been released in `0.14.0`. 🎉 

Two changes to `load`...

1. It now uses Ember Data to load the relationship, meaning it will respect your payloads relationship links.
2. `load` now returns a promise that resolves with the relationship.

**Comment by mwpastore** [comment]
Hi folks, I'm working on an Ember project after a bit of an absence. LoadableModel#load works great! But I still can't perform inline filter/sort/page operations. There's discussion above about adding LoadableModel#query; has that been dropped or is it still an open topic?

**Comment by ryanto** [comment]
Hi Mike, welcome back!

There's been a few requests for a query-relationship-with-params API, but tbh I'm not sure how to best do it. I always end up with a bunch of adapter overrides that I'm not comfortable with shipping. Fwiw, this can be done in 3.4+ w/o any addons. Take a look at the options param that was added the the references API... I can help you add that to your app if you're interested.

In our apps we're letting the front end make a lot of assumptions about the backend when querying a relationship. For example if we need a post's first 10 comments we would use something like...

```js
this.store.loadAll('comments', {
  filter: {
    post_id: post.id
  },
  page: {
    limit: 10,
    offset: 0
  }
});
```

Not ideal, it's a little brittle because it assumes the relationship/key id. However, this is what we feel best using given our JSON:API compliant backend.

Also it might be worth sticking with https://github.com/mdehoog/ember-data-has-many-query if that currently works.
