### ISSUE TITLE
Do loadAll() and loadRecord() share the same cache/logic?

### ISSUE THREAD

**Issue by bravo-kernel** [embermap/ember-data-storefront#35]
Should the following work or am I chasing something impossible here?

1. First connect to `/projects` using `loadAll()` (not including related data)
2. Then connect to `/projects/1` using `loadRecord()` which has an `include` option

I would expect step 2 to automatically fetch the related data (as this query is not Storefront cached) but nothing happens, my API is not called. I am testing with these most basic routes:

```js
// projects route
export default Route.extend({
  model() {
    return this.store.loadAll('project').then(results => results.sortBy('name'));
  }
});
```

```js
export default Route.extend({
  model(params) {
    return this.store.loadRecord('project', params.project_id, { include: 'project-members' });
  }
});
```
Much appreciated

**Comment by ryanto** [comment]
How are you going from `/projects` to `/projects/1`? Are you using link-to?

**Comment by bravo-kernel** [comment]
yes, using a `link-to`

**Comment by bravo-kernel** [comment]
The other way around does work exactly like the guide explains:

1. loads all related data for e.g. `/projects/2`
2. clicking the link back to `/projects` now shows all projects

However, then browsing to e.g. `/projects/2` does not load related data for that project

**Comment by ryanto** [comment]
Model hooks do not run when using `{{link-to}}` when given a model. The guides outline this: https://guides.emberjs.com/v3.0.0/routing/specifying-a-routes-model/#toc_dynamic-models It's extremely confusing

> Note: A route with a dynamic segment will always have its model hook called when it is entered via the URL. If the route is entered through a transition (e.g. when using the link-to Handlebars helper), and a model context is provided (second argument to link-to), then the hook is not executed. If an identifier (such as an id or slug) is provided instead then the model hook will be executed.

A trick to make this work is to link-to the model's id, which will force the model hook to run.

```hbs
{{! wont run model hook }}
{{link-to "View project" "projects.show" project}}

{{! will run model hook }}
{{link-to "View project" "projects.show" project.id}}
```

Let me know if that clears it up.

**Comment by bravo-kernel** [comment]
Amazing, spot on and indeed... most confusing, I never expected that.

Do you think this should be added to the docs or will this ticket suffice for future/fellow noobs encountering the same issue?

**Comment by ryanto** [comment]
It should be added, it sounds like it would have helped you. If you want to PR it I'll make sure it gets merged.

**Comment by bravo-kernel** [comment]
Will do. Much obliged, awesome tool 💯
