### ISSUE TITLE
load resolves before models are loaded

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-data-storefront#37]
If a model has been loaded then `load('relationship')` resolves sync (next tick). Should be async.

**Comment by mwpastore** [comment]
Sorry to necro an old issue, but I'm having a similar issue on Ember Data 3.4.4 and I'm wondering if you figured out what was causing this?

**Comment by ryanto** [comment]
No worries! Could you share some sample code that's causing the issue. I can get a test case coded up.

**Comment by ryanto** [comment]
Hey @mwpastore! Wondering if this is still an issue for you. I'm going to close it for now, but feel free to reopen if it is.
