### ISSUE TITLE
force-sync doesn't work with destructured DS

### ISSUE THREAD

**Issue by mwpastore** [embermap/ember-data-storefront#4]
I use this syntax in my Ember Data model definitions:

```javascript
import Model from 'ember-data/model';

import attr from 'ember-data/attr';
import { belongsTo, hasMany } from 'ember-data/relationships';

export default Model.extend({
  foo: attr('string'),
  bars: hasMany(),
  qux: belongsTo()
});
```

Unfortunately, the way force-sync overrides DS.hasMany and DS.belongsTo has no effect on these methods.

**Comment by ryanto** [comment]
Nice find.

@samselikoff thoughts?

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-data-storefront/pull/13 closes.

Check out the "Sync relationships" section of https://embermap.github.io/ember-data-storefront/docs/guides/working-with-relationships for more, and let us know if you have any feedback 🙂

**Comment by mwpastore** [comment]
Neat! Thanks @samselikoff!
