### ISSUE TITLE
Docs: broken styles

### ISSUE THREAD

**Issue by ctjhoa** [embermap/ember-data-storefront#40]
Hi,

There is a documentation issue.
It looks messed up (in FF 59.0.1 & chrome 65.0.3325.181)
and in chrome you cannot scroll the main content.

![2018-04-05-071808_3839x2129_scrot](https://user-images.githubusercontent.com/1716173/38352084-88089728-38a1-11e8-863c-03e9014d7be7.png)
![2018-04-05-071906_3839x2131_scrot](https://user-images.githubusercontent.com/1716173/38352115-a5148d40-38a1-11e8-979b-febbe65782d7.png)

**Comment by ryanto** [comment]
Thanks! Try mousing over the main content before scrolling, does that help?

There's a PR that's a work in progress to fix this: https://github.com/embermap/ember-data-storefront/pull/36

**Comment by samselikoff** [comment]
@ctjhoa could you see if the new site has fixed it? https://embermap.github.io/ember-data-storefront/latest/

**Comment by ctjhoa** [comment]
Yeah the new one is better.
However, I have found one bug on the "LoadableStore" page.
![2018-04-10-112415_3839x2153_scrot](https://user-images.githubusercontent.com/1716173/38554332-bc9a4f18-3cb1-11e8-8e83-c87eb7b1e760.png)
![2018-04-10-112516_3833x2067_scrot](https://user-images.githubusercontent.com/1716173/38554364-dc882188-3cb1-11e8-95d1-f6aee3729f24.png)

The main content is truncated

**Comment by ctjhoa** [comment]
Thoses bugs are now fixed so I close this issue.

**Comment by samselikoff** [comment]
Thanks!
