### ISSUE TITLE
Template not updating when `loadRecord` resolves

### ISSUE THREAD

**Issue by engwan** [embermap/ember-data-storefront#46]
I'm using an `account` service where I load a user from the API based on the session user_id (ember-simple-auth).

It's something like:

    export default Service.extend({
      session: service(),

      user: computed('session.data.authenticated.user_id', function() {
        const user_id = this.get('session.data.authenticated.user_id');

        if (!isEmpty(user_id)) {                            
          return this.get('store').loadRecord('user', user_id);
        }                                                       
      })
    });

If I use `findRecord` there, it works fine. I do `{{account.user.name}}` in the template and it show up okay. If I use `loadRecord`, I'm not sure why it doesn't show anything.

I see the request being made correctly and returning the right data. When I look at the "Data" tab in ember-inspector, the user is also loaded correctly.

So I'm assuming it's handlebars not detecting the promise resolved and the value needs to be updated. Is there something I'm missing here?

Thanks

**Comment by ryanto** [comment]
Closing for now, but happy to keep working on this if there's interest
