### ISSUE TITLE
sync hasMany relationship not live? 

### ISSUE THREAD

**Issue by mwpastore** [embermap/ember-data-storefront#61]
Sorry to use this channel for help, but I'm stuck and confused. Ember 3.6.0-beta.4, Ember Data 3.4.4, ember-data-storefront 0.14.2.

My model hook looks like this:

```javascript
async model() {
  const { foo } = this.modelFor('some-parent-route');

  await foo.reloadWith('bars');

  return { bars: foo.get('bars') };
}
```

When I navigate to this route and foo.bars has previously been loaded, Model#reloadWith returns immediately, which is fine. The ajax call fires and fetches some additional records in the background. However, model.bars in my controller never updates with the additional records... it seems that the sync hasMany relationship is not a live array? 

```javascript
@computed('model.bars.[]')
get barsLength() {
  // fires once with the initial count, but never a second time with the updated count
  console.log(this.model.bars.length);
}
```

Is this the intended behavior? Is there another pattern I should be using? Thank you in advance.

**Comment by ryanto** [comment]
Thanks for the issue - I'll setup a code sandbox where we can experiment. 

If you reduce this model hook code to only use Ember Data, does it start working?

```js
async model() {
  const { foo } = this.modelFor('some-parent-route');

  await store.findRecord('foo', foo.id, { include: 'bars' });

  return { bars: foo.get('bars') };
}
```

**Comment by mwpastore** [comment]
Thanks @ryanto! 

The plot thickens... yes, it starts working when I do it that way instead.

**Comment by ryanto** [comment]
Ah that's strange! Could you reproduce this in an acceptance test? That will be the easiest way for us to fix this. Feel free to make a brand new acceptance test that captures this scenario.

Also, if it's easier to make a code sandbox instead of a test, check out the mirage sandbox as a starting point https://codesandbox.io/s/003o6pq34n

**Comment by mwpastore** [comment]
This is no longer an issue in newer versions of Ember Data, so whether it's worthwhile to pursue a fix for Ember Data 3.4.4 is left as an exercise for the reader. 😉

**Comment by ryanto** [comment]
Glad to hear!

**Comment by mwpastore** [comment]
Aaaaand it's back in Ember Data 3.9.2. Would you please re-open? I'll work on that acceptance test... grumble grumble
