### ISSUE TITLE
Issues with saving and relationships becoming unset.

### ISSUE THREAD

**Issue by Duder-onomy** [embermap/ember-data-storefront#67]
Hi, 
We are SUPER excited to start using sync relationships with loadable models. Excited to learn more at the Pre Ember Conf Session. Please let me know if this does not belong here, I find the discord channel to be tiresome. 

We are just dipping our toes into using loadable models and sync relationships, everything seems to work great UNTIL, we save the record. 

We are using JSON API and the JSON API Resources Gem.

Lets say we have a loadable model with all relationships set to async: false
When we save that record, with relationships, everything posts correct. Our api returns that record as per the jsonapi spec WITH the relationship defined, but without the relationship data:
Something like this is returned:
```
{
  "type": "bookings",
  "id": "1",
  "attributes": {
    "title": "Ember Data Rawk"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
    }
  },
  "links": {
    "self": "http://example.com/articles/1"
  }
}
```
Because that relationship no longer has the `data` attribute, ember will wipe the record from our local store. This only happens when we have loadable models with async: false relationships. 

I have a feeling that it works when we are not using async: false because accessing the relationship will re-fetch the record from the store. Setting async: false, tells ember to assume that the relationship will always be there, and thus, when a record is returned with empty relations, the relations (and their underlying data) are wiped from the store. 

Do you know how to prevent ember from crushing the relationship? Have you run into this and how did you solve it?

**Comment by ryanto** [comment]
Hi Duder!

Thanks for opening the issue, this is the perfect place for it!

I have two thoughts...

1. Do you know if this is a Storefront bug or an Ember Data bug? Does it happen with any model that has `sync` relationships, or only ones that have `LoadableModel` mixed in?

2. We use the JSON:API Resources gem as well and it always includes links, even if those URLs don't exist on the backend. If all of your relationships are sync, then I would recommend using the application serializer to filter out these links. Here's what we do in EmberMap's codebase: https://gist.github.com/ryanto/7d12b8f53af2870a1e502b194f10e5d7 Let me know if this makes sense, happy to dive a little deeper here.

Excited to meet you in Portland!

**Comment by Duder-onomy** [comment]
Wooooooo! Awesome. 
IMO, it was not a _bug_ in Ember Data or Storefront, I think it is just the default behavior of both ember data + json api + async: false relationships. When a response is serialized with the relationship links, ember will treat those as the canonical data and wipe out anything you have in your store.

That serializer fixed everything for me and I am flying. Thanks so much. Might be worth putting in the docs if anyone gets here with the same prob. 

Anyhow. Thanks again!

**Comment by samselikoff** [comment]
@Duder-onomy thanks so much for opening the issue 🙌

We are planning on tackling this soon and will definitely be updating the docs. Key is to make sure we understand what assumptions Ember Data's making when you set async to false and go from there.

Keep us updated on your progress and anything new you discover!

**Comment by ryanto** [comment]
Quick update! 

If anyone else is running into this, here's a PR to Ember Data to change it's sync relationship behavior: https://github.com/emberjs/data/pull/5880
