### ISSUE TITLE
Does not work with engines

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-data-storefront#68]
Hey @frank06 I'm adding an issue here since I don't have an answer for this: https://github.com/embermap/ember-data-storefront/pull/17

Storefront adds methods to Ember Data's store and because of this it needs to run in an initializer after Ember Data has created its store. This does not work inside of an engine.

Storefront's initializer: https://github.com/embermap/ember-data-storefront/blob/master/addon/instance-initializers/mixin-storefront.js
Data's initializer: https://github.com/emberjs/data/blob/master/addon/initialize-store-service.js

If anyone has any ideas how to fix this I'd love to hear. Maybe there are alternatives that don't involve using an initializer or mixin?

**Comment by Duder-onomy** [comment]
FWIW. I don't think this is true.  In the app I work on, ( heavily engine ified ), ember-data-storefront works correct. 
In our app, and I suspect most, we share the store from the parent app into the engine.

**Comment by ryanto** [comment]
Oh that's good to hear! Thanks @Duder-onomy 

@frank06 how are you using this addon with engines? I've never used ember-engines, so I'm a little out of water here. If you could share a minimal engine app that doesn't work with storefront that would help me get this fixed.

**Comment by frank06** [comment]
@ryanto Sorry I totally missed this question and I'm no longer on that project. I recall there definitely was an issue and we ended up not using Storefront in engines. If I am able to gather more info or reproduce I'll let you know!

**Comment by ryanto** [comment]
Hey Frank, no problem! It certainly wouldn't surprise me if there are some issues with engines.

I'm going to close this since I don't think there's anything I can do about it right now. If anyone reading this is having an issue with engines feel free to bump this!
