### ISSUE TITLE
Not compatible with Ember Octane

### ISSUE THREAD

**Issue by mwpastore** [embermap/ember-data-storefront#72]
I've added a failing ember-try scenario here: #73 

UPDATE: I've managed to fix an issue with Ember Data that was preventing this addon from working in canary, with or without jQuery. Now it seems to work fine, but there are still failing tests.

**Comment by ryanto** [comment]
I think the failing tests are because we use liquid-fire, which depends on jQuery. Left a comment in #73 about that.

Thanks for fixing the ED issue upstream too! 🔥
