### ISSUE TITLE
Better call site info in error message?

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-data-storefront#78]
Upgraded to 0.16 and got this error

![image](https://user-images.githubusercontent.com/2922250/57084442-506b9e80-6cc8-11e9-846e-69e4f4da184e.png)

If I double-click on stack I see this

![image](https://user-images.githubusercontent.com/2922250/57084464-5bbeca00-6cc8-11e9-8214-b14fe742f528.png)

I wonder if it's possible for us to show in the application code where the source of the call is.

**Comment by samselikoff** [comment]
Believe this might be a bug as well, https://github.com/embermap/ember-data-storefront/blob/4c26a29fa3189ab6a9153148144f4a477d68ac69/addon/mixins/loadable-model.js#L183 assertion here might not be working for polymorphic relationships.

**Comment by ryanto** [comment]
This is part of Ember.assert? Should we use something else?

**Comment by samselikoff** [comment]
Not sure but this really bothers me in other libs too. The thing in the stack is actually what I want reported to the console.

Maybe we're supposed to rerun with `no-try-catch` enabled? Not sure what's possible

**Comment by samselikoff** [comment]
Nothing actionable for now but it really bothers me
